### ISSUE TITLE
any way to use galaxykit to approve collections?

### ISSUE THREAD

**Issue by kdelee** [ansible/galaxykit#36]
I'm trying to use an old script that used to do the following to find collections that need approving and approve them:

```
def approve_collections(session):
    while True:
        # This lists only latest not approved versions for every namespace.name
        uri = "/api/galaxy/content/staging/v3/collections/"
        result = session.get_all(uri=uri)
        if len(result) == 0:
            print("No session found, aborting...")
            break

        logging.debug(f"Processing {len(result)} collection highest versions")
        for c in result:
            c_namespace = c['namespace']
            c_name = c['name']
            c_version = c['highest_version']['version']

            # Start approval process
            uri = f"/api/galaxy/v3/collections/{c_namespace}/{c_name}/versions/{c_version}/move/staging/published/"
            result = session.post(uri=uri)

            # Wait for all approval related tasks finishes
            session.task_wait(result['remove_task_id'])
            session.task_wait(result['copy_task_id'])

            logging.info(f"Collection {c_namespace}.{c_name}:{c_version} approved")
```

needless to say...I wouldn't be here if this worked. But its not finding anything at `/api/galaxy/content/staging/v3/collections/` so I'm trying to figure out how to re-implement this in a way that works, and I'm wondering when/how the API changed

**Comment by ironfroggy** [comment]
That should still be valid for an install with the API at `/api/galaxy/` like that.

Does anything come up for the stage repo API root at `/api/automation-hub/content/staging/`?

**Comment by kdelee** [comment]
![Screenshot from 2022-03-30 16-13-34](https://user-images.githubusercontent.com/29239279/160922942-60e49fc2-dde6-4b58-8547-f127b282804a.png)
api looks like it si on /api/galaxy, not /api/automation-hub

**Comment by hendersonreed** [comment]
@kdelee there's `galaxykit.collections.collection_move()` which handles moving collections from repo to repo. But if you aren't seeing collections on `/api/galaxy/content/staging/v3/collections/` then I suspect there's something else going on.
